function t461_setLogoPadding(recid){if($(window).width()>980){var t461__menu=$('#rec'+recid+' .t461');var t461__logo=t461__menu.find('.t461__logowrapper');var t461__leftpart=t461__menu.find('.t461__leftwrapper');var t461__rightpart=t461__menu.find('.t461__rightwrapper');t461__leftpart.css("padding-right",t461__logo.width()/2+50);t461__rightpart.css("padding-left",t461__logo.width()/2+50)}}
function t461_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t461__list_item a[href='"+url+"']").addClass("t-active");$(".t461__list_item a[href='"+url+"/']").addClass("t-active");$(".t461__list_item a[href='"+pathname+"']").addClass("t-active");$(".t461__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t461__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t461__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t461_checkAnchorLinks(recid){if($(window).width()>=960){var t461_navLinks=$("#rec"+recid+" .t461__desktoplist .t461__list_item a:not(.tooltipstered)[href*='#']");if(t461_navLinks.length>0){t461_catchScroll(t461_navLinks)}}}
function t461_catchScroll(t461_navLinks){var t461_clickedSectionId=null,t461_sections=new Array(),t461_sectionIdTonavigationLink=[],t461_interval=100,t461_lastCall,t461_timeoutId;t461_navLinks=$(t461_navLinks.get().reverse());t461_navLinks.each(function(){var t461_cursection=t461_getSectionByHref($(this));if(typeof t461_cursection.attr("id")!="undefined"){t461_sections.push(t461_cursection)}
t461_sectionIdTonavigationLink[t461_cursection.attr("id")]=$(this)});t461_updateSectionsOffsets(t461_sections);t461_sections.sort(function(a,b){return b.attr("data-offset-top")-a.attr("data-offset-top")});$(window).bind('resize',t_throttle(function(){t461_updateSectionsOffsets(t461_sections)},200));$('.t461').bind('displayChanged',function(){t461_updateSectionsOffsets(t461_sections)});setInterval(function(){t461_updateSectionsOffsets(t461_sections)},5000);t461_highlightNavLinks(t461_navLinks,t461_sections,t461_sectionIdTonavigationLink,t461_clickedSectionId);t461_navLinks.click(function(){var t461_clickedSection=t461_getSectionByHref($(this));if(!$(this).hasClass("tooltipstered")&&typeof t461_clickedSection.attr("id")!="undefined"){t461_navLinks.removeClass('t-active');$(this).addClass('t-active');t461_clickedSectionId=t461_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t461_now=new Date().getTime();if(t461_lastCall&&t461_now<(t461_lastCall+t461_interval)){clearTimeout(t461_timeoutId);t461_timeoutId=setTimeout(function(){t461_lastCall=t461_now;t461_clickedSectionId=t461_highlightNavLinks(t461_navLinks,t461_sections,t461_sectionIdTonavigationLink,t461_clickedSectionId)},t461_interval-(t461_now-t461_lastCall))}else{t461_lastCall=t461_now;t461_clickedSectionId=t461_highlightNavLinks(t461_navLinks,t461_sections,t461_sectionIdTonavigationLink,t461_clickedSectionId)}})}
function t461_updateSectionsOffsets(sections){$(sections).each(function(){var t461_curSection=$(this);t461_curSection.attr("data-offset-top",t461_curSection.offset().top)})}
function t461_getSectionByHref(curlink){var t461_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(t461_curLinkValue[0]=='/'){t461_curLinkValue=t461_curLinkValue.substring(1)}
if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t461_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t461_curLinkValue.substring(1)+"']")}}
function t461_highlightNavLinks(t461_navLinks,t461_sections,t461_sectionIdTonavigationLink,t461_clickedSectionId){var t461_scrollPosition=$(window).scrollTop(),t461_valueToReturn=t461_clickedSectionId;if(t461_sections.length!=0&&t461_clickedSectionId==null&&t461_sections[t461_sections.length-1].attr("data-offset-top")>(t461_scrollPosition+300)){t461_navLinks.removeClass('t-active');return null}
$(t461_sections).each(function(e){var t461_curSection=$(this),t461_sectionTop=t461_curSection.attr("data-offset-top"),t461_id=t461_curSection.attr('id'),t461_navLink=t461_sectionIdTonavigationLink[t461_id];if(((t461_scrollPosition+300)>=t461_sectionTop)||(t461_sections[0].attr("id")==t461_id&&t461_scrollPosition>=$(document).height()-$(window).height())){if(t461_clickedSectionId==null&&!t461_navLink.hasClass('t-active')){t461_navLinks.removeClass('t-active');t461_navLink.addClass('t-active');t461_valueToReturn=null}else{if(t461_clickedSectionId!=null&&t461_id==t461_clickedSectionId){t461_valueToReturn=null}}
return!1}});return t461_valueToReturn}
function t461_setPath(){}
function t461_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t461").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t461").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t461_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t461").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t461_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t461").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t461_createMobileMenu(recid){var el=$("#rec"+recid);var menu=el.find(".t461");var burger=el.find(".t461__mobile");burger.on('click',function(e){$(menu).fadeToggle(300);$(this).toggleClass("t461_opened")});$(window).on('resize',t_throttle(function(){if($(window).width()>980){$(menu).fadeIn(0)}}))}
function t670_init(recid){t670_imageHeight(recid);t670_show(recid);t670_hide(recid)}
function t670_show(recid){var rec=document.getElementById('rec'+recid);var playBtns=rec.querySelectorAll('.t670__play');Array.prototype.forEach.call(playBtns,function(play){play.addEventListener('click',function(){var videoType=play.getAttribute('data-slider-video-type');var url;var nextEl;var prevEl;var iframe;switch(videoType){case 'youtube':url=play.getAttribute('data-slider-video-url');nextEl=play.nextElementSibling;prevEl=play.previousElementSibling.previousElementSibling;if(nextEl){iframe=document.createElement('iframe');iframe.classList.add('t670__iframe');iframe.width='100%';iframe.height='100%';iframe.src='https://www.youtube.com/embed/'+url+'?autoplay=1&enablejsapi=1';iframe.frameBorder='0';iframe.setAttribute('webkitallowfullscreen','');iframe.setAttribute('mozallowfullscreen','');iframe.setAttribute('allowfullscreen','');iframe.setAttribute('allow','autoplay');nextEl.innerHTML='';nextEl.insertAdjacentElement('beforeend',iframe)}
if(prevEl&&prevEl.classList.contains('t-bgimg'))prevEl.style.opacity='0';break;case 'vimeo':url=play.getAttribute('data-slider-video-url');nextEl=play.nextElementSibling;prevEl=play.previousElementSibling.previousElementSibling;var idMatch=/vimeo[^/]*\/(\d+)\/?(\w*)\/?/i.exec(url);var id=idMatch?idMatch[1]:null;var hash=idMatch?'?h='+idMatch[2]:null;if(nextEl){iframe=document.createElement('iframe');iframe.classList.add('t670__iframe');iframe.width='100%';iframe.height='100%';iframe.src='https://player.vimeo.com/video/'+id+hash+'&amp;api=1';iframe.frameBorder='0';iframe.setAttribute('allowfullscreen','');iframe.setAttribute('allow','autoplay; fullscreen');nextEl.innerHTML='';nextEl.insertAdjacentElement('beforeend',iframe)}
if(prevEl&&prevEl.classList.contains('t-bgimg'))prevEl.style.opacity='0';break}
if(nextEl)nextEl.style.zIndex='3'})})}
function t670_hide(recid){var rec=document.getElementById('rec'+recid);var elBody=rec.querySelector('.t670__frame');rec.addEventListener('updateSlider',function(){if(elBody)elBody.innerHTML='';if(elBody)elBody.style.zIndex=''})}
function t670_imageHeight(recid){var rec=document.getElementById('rec'+recid);var images=rec.querySelectorAll('.t670__separator');Array.prototype.forEach.call(images,function(img){var width=img.getAttribute('data-slider-image-width')||0;var height=img.getAttribute('data-slider-image-height')||0;var ratio=height/width;var padding=ratio*100;img.style.paddingBottom=padding+'%'})}
function t754__init(recid){setTimeout(function(){t_onFuncLoad('t_prod__init',function(){t_prod__init(recid)});t754__hoverZoom_init(recid);t754_initPopup(recid);t754__updateLazyLoad(recid);t754__alignButtons_init(recid);if(typeof t_store_addProductQuantityEvents!=='undefined'){t754_initProductQuantity(recid)}
$('body').trigger('twishlist_addbtn')},500)}
function t754_initProductQuantity(recid){var el=$('#rec'+recid);var productList=el.find(".t754__col, .t754__product-full");productList.each(function(i,product){t_store_addProductQuantityEvents($(product))})}
function t754__showMore(recid){var el=$('#rec'+recid).find(".t754");var showmore=el.find('.t754__showmore');var cards_count=parseInt(el.attr('data-show-count'),10);if(cards_count>0){if(showmore.text()===''){showmore.find('td').text(t754__dict('loadmore'))}
showmore.show();el.find('.t754__col').hide();var cards_size=el.find('.t754__col').size();var cards_count=parseInt(el.attr('data-show-count'),10);var x=cards_count;var y=cards_count;t754__showSeparator(el,x);el.find('.t754__col:lt('+x+')').show();showmore.click(function(){x=(x+y<=cards_size)?x+y:cards_size;el.find('.t754__col:lt('+x+')').show();if(x==cards_size){showmore.hide()}
if(typeof $('.t-records').attr('data-tilda-mode')=='undefined'){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
t754__showSeparator(el,x);if($('#rec'+recid).find('[data-buttons-v-align]')[0]){t754__alignButtons(recid)}})}}
function t754__showSeparator(el,x){el.find('.t754__separator_number').addClass('t754__separator_hide');el.find('.t754__separator_hide').each(function(){if($(this).attr('data-product-separator-number')<=x){$(this).removeClass('t754__separator_hide')}})}
function t754__dict(msg){var dict=[];dict.loadmore={EN:'Load more',RU:'Загрузить еще',FR:'Charger plus',DE:'Mehr laden',ES:'Carga más',PT:'Carregue mais',UK:'Завантажити ще',JA:'もっと読み込む',ZH:'裝載更多',};var lang=window.browserLang;if(typeof dict[msg]!=='undefined'){if(typeof dict[msg][lang]!=='undefined'&&dict[msg][lang]!=''){return dict[msg][lang]}else{return dict[msg].EN}}
return 'Text not found "'+msg+'"'}
function t754__alignButtons_init(recid){var el=$('#rec'+recid);if(el.find('[data-buttons-v-align]')[0]){try{t754__alignButtons(recid);$(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!=='undefined'&&window.noAdaptive===!0&&$isMobile){return}
t754__alignButtons(recid)},200));el.find('.t754').bind('displayChanged',function(){t754__alignButtons(recid)});if($isMobile){$(window).on('orientationchange',function(){t754__alignButtons(recid)})}}catch(e){console.log('buttons-v-align error: '+e.message)}}}
function t754__alignButtons(recid){var rec=$('#rec'+recid);var wrappers=rec.find('.t754__textwrapper');var maxHeight=0;var itemsInRow=rec.find('.t-container').attr('data-blocks-per-row')*1;var mobileView=$(window).width()<=480;var tableView=$(window).width()<=960&&$(window).width()>480;var mobileOneRow=$(window).width()<=960&&rec.find('.t754__container_mobile-flex')[0]?!0:!1;var mobileTwoItemsInRow=$(window).width()<=480&&rec.find('.t754 .mobile-two-columns')[0]?!0:!1;if(mobileView){itemsInRow=1}
if(tableView){itemsInRow=2}
if(mobileTwoItemsInRow){itemsInRow=2}
if(mobileOneRow){itemsInRow=999999}
var i=1;var wrappersInRow=[];$.each(wrappers,function(key,element){element.style.height='auto';if(itemsInRow===1){element.style.height='auto'}else{wrappersInRow.push(element);if(element.offsetHeight>maxHeight){maxHeight=element.offsetHeight}
$.each(wrappersInRow,function(key,wrapper){wrapper.style.height=maxHeight+'px'});if(i===itemsInRow){i=0;maxHeight=0;wrappersInRow=[]}
i++}})}
function t754__hoverZoom_init(recid){if(isMobile){return}
var rec=$('#rec'+recid);try{if(rec.find('[data-hover-zoom]')[0]){if(!jQuery.cachedZoomScript){jQuery.cachedZoomScript=function(url){var options={dataType:'script',cache:!0,url:url};return jQuery.ajax(options)}}
$.cachedZoomScript('https://static.tildacdn.com/js/tilda-hover-zoom-1.0.min.js').done(function(script,textStatus){if(textStatus=='success'){setTimeout(function(){t_hoverZoom_init(recid,".t-slds__container")},500)}else{console.log('Upload script error: '+textStatus)}})}}catch(e){console.log('Zoom image init error: '+e.message)}}
function t754__updateLazyLoad(recid){var scrollContainer=$("#rec"+recid+" .t754__container_mobile-flex");var curMode=$(".t-records").attr("data-tilda-mode");if(scrollContainer.length&&curMode!="edit"&&curMode!="preview"){scrollContainer.bind('scroll',t_throttle(function(){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}))}}
function t754_initPopup(recid){var rec=$('#rec'+recid);rec.find('[href^="#prodpopup"]').one("click",function(e){e.preventDefault();var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid+' #t754__product-'+lid_prod+'')})});rec.find('[href^="#prodpopup"]').click(function(e){e.preventDefault();if($(e.target).hasClass('t1002__addBtn')||$(e.target).parents().hasClass('t1002__addBtn')){return}
t754_showPopup(recid);var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');el_popup.find('.js-product').css('display','none');var el_fullprod=el_popup.find('.js-product[data-product-lid="'+lid_prod+'"]');el_fullprod.css('display','block');var analitics=el_popup.attr('data-track-popup');if(analitics>''){var virtTitle=el_fullprod.find('.js-product-name').text();if(!virtTitle){virtTitle='prod'+lid_prod}
Tilda.sendEventToStatistics(analitics,virtTitle)}
var curUrl=window.location.href;if(curUrl.indexOf('#!/tproduct/')<0&&curUrl.indexOf('%23!/tproduct/')<0&&curUrl.indexOf('#%21%2Ftproduct%2F')<0){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tproduct/'+recid+'-'+lid_prod)}}
t754_updateSlider(recid+' #t754__product-'+lid_prod+'');if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}});if($('#record'+recid).length==0){t754_checkUrl(recid)}
t754_copyTypography(recid)}
function t754_checkUrl(recid){var curUrl=window.location.href;var tprodIndex=curUrl.indexOf('#!/tproduct/');if(tprodIndex<0){tprodIndex=curUrl.indexOf('%23!/tproduct/');if(tprodIndex<0){tprodIndex=curUrl.indexOf('#%21%2Ftproduct%2F')}}
if(tprodIndex>=0){var curUrl=curUrl.substring(tprodIndex,curUrl.length);var curProdLid=curUrl.substring(curUrl.indexOf('-')+1,curUrl.length);var rec=$('#rec'+recid);if(curUrl.indexOf(recid)>=0&&rec.find('[data-product-lid='+curProdLid+']').length){rec.find('[data-product-lid='+curProdLid+'] [href^="#prodpopup"]').triggerHandler('click')}}}
function t754_updateSlider(recid){var el=$('#rec'+recid);t_onFuncLoad('t_slds_SliderWidth',function(){t_slds_SliderWidth(recid)});var sliderWrapper=el.find('.t-slds__items-wrapper');var sliderWidth=el.find('.t-slds__container').width();var pos=parseFloat(sliderWrapper.attr('data-slider-pos'));sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'});t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)})}
function t754_showPopup(recid){var el=$('#rec'+recid);var popup=el.find('.t-popup');popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show');if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},50);$('body').addClass('t-body_popupshowed');$('body').trigger('twishlist_addbtn');el.find('.t-popup').mousedown(function(e){var windowWidth=$(window).width();var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(e.clientX>windowWithoutScrollBar){return}
if(e.target==this){t754_closePopup()}});el.find('.t-popup__close, .t754__close-text').click(function(e){t754_closePopup()});$(document).keydown(function(e){if(e.keyCode==27){t754_closePopup()}})}
function t754_closePopup(){$('body').removeClass('t-body_popupshowed');$('.t-popup').removeClass('t-popup_show');$('body').trigger('twishlist_addbtn');var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=curUrl.indexOf('%23!/tproduct/');if(indexToRemove<0){indexToRemove=curUrl.indexOf('#%21%2Ftproduct%2F')}}
curUrl=curUrl.substring(0,indexToRemove);setTimeout(function(){$(".t-popup").scrollTop(0);$('.t-popup').not('.t-popup_show').css('display','none');if(typeof history.replaceState!='undefined'){window.history.replaceState('','',curUrl)}},300)}
function t754_removeSizeStyles(styleStr){if(typeof styleStr!="undefined"&&(styleStr.indexOf('font-size')>=0||styleStr.indexOf('padding-top')>=0||styleStr.indexOf('padding-bottom')>=0)){var styleStrSplitted=styleStr.split(';');styleStr="";for(var i=0;i<styleStrSplitted.length;i++){if(styleStrSplitted[i].indexOf('font-size')>=0||styleStrSplitted[i].indexOf('padding-top')>=0||styleStrSplitted[i].indexOf('padding-bottom')>=0){styleStrSplitted.splice(i,1);i--;continue}
if(styleStrSplitted[i]==""){continue}
styleStr+=styleStrSplitted[i]+";"}}
return styleStr}
function t754_copyTypography(recid){var rec=$('#rec'+recid);var titleStyle=rec.find('.t754__title').attr('style');var descrStyle=rec.find('.t754__descr').attr('style');rec.find('.t-popup .t754__title').attr("style",t754_removeSizeStyles(titleStyle));rec.find('.t-popup .t754__descr, .t-popup .t754__text').attr("style",t754_removeSizeStyles(descrStyle))}